name: compile-latex-documents
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        working-directory: ./ProblemSets_PartI
        uses: dante-ev/latex-action@latest
        with:
          root_file: Math227C20Sp_P1.tex
          compiler: pdflatex
